ci: setup production-grade continuous integration pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,7 +2,7 @@ name: SNCF API CI Pipeline
 
 on:
     push:
-        branches: ["main"]
+        branches: ["test-ci"]
     pull_request:
         branches: ["main"]
 
@@ -11,19 +11,45 @@ jobs:
         runs-on: ubuntu-latest
 
         steps:
-            - uses: actions/checkout@v4
+            - name: Checkout code
+              uses: actions/checkout@v4
             - name: Set up Python3.1
               uses: actions/setup-python@v5
               with:
                 python-version: '3.10'
-                architecture: 'x64'     # Optional - x64 or x86 architecture, defaults to x64
+                architecture: 'x64'  
+                cache: 'pip'   # Optional - x64 or x86 architecture, defaults to x64
                 
-            - run: |
+            - name: Install the libraries
+              run: |
                 python -m pip install --upgrade pip 
                 pip install -r requirements.txt  
+                pip install pytest httpx
             
             - name: Display Python version
               run: python -c "import sys; print(sys.version)"
+
+            - name: Check Model Artifacts
+              run: |
+                if [! -d "production_model"]; then 
+                  echo "Error: The 'production_model' directory does not exist!"
+                  exit 1
+                fi 
+
+                if [! -d "production_model/model.pkl"]; then
+                  echo "Error: The 'model.pkl' does not exist!"
+                  exit 1
+                fi
+                echo "All model artifacts have been found!"
+
+            - name: Unit Testing
+              run: |
+                pytest test_api.py -v
+            
+            - name: Check the Docker build process.
+              run: |
+                docker build -t sncf-delay-mlops-app:test .
+                echo "Docker build successful! Ready for production."
             
 
 
